[package]
name = "gores-mapgen-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = "0.15.0"
egui = "0.21.0"
egui-miniquad = "0.14.0"
macroquad = { version="0.3.25", default-features=false }

[features]
default = ["audio"]
audio = ["macroquad/audio"]

[profile.release]
opt-level = 2
